version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_ROOT_DATABASE: babo
    container_name: babo
    ports:
      - 3306:3306